DELETE http://localhost:3003/api/blogs/65037a1bb06c9e5353eb46ff
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFudHRpMTIzIiwiaWQiOiI2NTA4YmYyZGIwZmYxMzY5NWY1MDBjNmQiLCJpYXQiOjE2OTUwNzIwNTMsImV4cCI6MTY5NTA3NTY1M30.WCarBWzQi9NNIqKXK7O2Md97OKb7RlVcVCIRj-4fQkU